<template>
  <router-link 
    :to="`/category/${category.autogeneratedSlug}`" 
    class="block bg-white rounded-lg shadow-md overflow-hidden transition-transform hover:shadow-lg hover:-translate-y-1"
  >
    <div class="h-32 overflow-hidden">
      <img
        v-if="category.imageUrl"
        :src="category.imageUrl"
        :alt="category.name"
        class="w-full h-full object-cover transition-transform hover:scale-105"
      />
      <div v-else class="w-full h-full bg-gray-100 flex items-center justify-center">
        <Icon icon="mdi:folder-outline" class="text-gray-300 w-12 h-12" />
      </div>
    </div>
    <div class="p-3">
      <h3 class="text-sm font-semibold text-center truncate">{{ category.name }}</h3>
      <p v-if="category.productCount" class="text-xs text-gray-500 text-center mt-1">
        <Icon icon="mdi:package-variant" class="inline-block w-3 h-3 mr-1" />
        {{ category.productCount }} products
      </p>
    </div>
  </router-link>
</template>

<script setup lang="ts">
import { Icon } from '@iconify/vue';
import type { Category } from '../../types/Category';

defineProps<{
  category: Category
}>();
</script> 