<template>
  <AppLayout>
    <div v-if="loading" class="flex justify-center my-12">
      <div class="loader"></div>
    </div>

    <div v-else-if="error" class="bg-red-100 text-red-700 p-4 rounded mb-6">
      {{ error }}
    </div>

    <template v-else>
      <!-- Category title if we're in a category -->
      <h1 v-if="currentCategory" class="text-2xl font-bold mb-6">
        {{ currentCategory.name }}
      </h1>
      <h1 v-else class="text-2xl font-bold mb-6">Product Catalog</h1>

      <!-- Categories list if we're on the main page -->
      <div v-if="!currentCategory && categories.length > 0" class="mb-8">
        <h2 class="text-xl font-semibold mb-4">Categories</h2>
        <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-4">
          <CategoryCard 
            v-for="category in categories" 
            :key="category.id" 
            :category="category" 
          />
        </div>
      </div>

      <!-- Products list -->
      <div>
        <h2 class="text-xl font-semibold mb-4">Products</h2>
        <div v-if="products.length > 0" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6">
          <ProductCard 
            v-for="product in products" 
            :key="product.id" 
            :product="product" 
          />
        </div>
        <div v-else class="text-center py-12 text-gray-500">
          <Icon icon="mdi:package-variant-remove" class="w-12 h-12 mx-auto mb-2" />
          No products found
        </div>
      </div>
    </template>
  </AppLayout>
</template>

<script setup lang="ts">
import { computed, onMounted, watchEffect, watch } from 'vue';
import { useRoute } from 'vue-router';
import { Icon } from '@iconify/vue';
import { useHead } from '@vueuse/head';
import { useCatalogStore } from '../stores/catalog';
import AppLayout from '../components/layout/AppLayout.vue';
import ProductCard from '../components/product/ProductCard.vue';
import CategoryCard from '../components/product/CategoryCard.vue';
import type { Category } from '../types/Category';
import type { Product } from '../types/Product';

const route = useRoute();
const catalogStore = useCatalogStore();

const loading = computed(() => catalogStore.loading);
const error = computed(() => catalogStore.error);
const categories = computed<Category[]>(() => catalogStore.categories);
const products = computed<Product[]>(() => catalogStore.products);

const categorySlug = computed(() => {
  return route.params.id ? String(route.params.id) : undefined;
});

const currentCategory = computed<Category | null>(() => {
  if (!categorySlug.value) return null;
  return categories.value.find(category => category.autogeneratedSlug === categorySlug.value) || null;
});

// Реактивные SEO метаданные
const title = computed(() => 
  currentCategory.value 
    ? (currentCategory.value.seoTitle || currentCategory.value.name) 
    : 'Product Catalog'
);

const description = computed(() => 
  currentCategory.value 
    ? (currentCategory.value.seoDescription || '') 
    : 'Browse our products catalog'
);

// Применяем метаданные с помощью useHead
useHead({
  title,
  meta: [
    {
      name: 'description',
      content: description
    }
  ]
});

onMounted(async () => {
  await catalogStore.fetchCategories();
});

watchEffect(async () => {
  const categoryId = currentCategory.value?.id;
  await catalogStore.fetchProducts(categoryId);
});
</script>

<style scoped>
.loader {
  border: 4px solid rgba(0, 0, 0, 0.1);
  border-radius: 50%;
  border-top: 4px solid #3b82f6;
  width: 40px;
  height: 40px;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style> 