export interface Category {
  id: number;
  name: string;
  url?: string;
  description?: string;
  imageUrl?: string;
  orderBy: number;
  parentId?: number;
  productCount?: number;
  autogeneratedSlug?: string;
  seoTitle?: string;
  seoDescription?: string;
}

export interface CategoryResponse {
  total: number;
  count: number;
  offset: number;
  limit: number;
  items: Category[];
} 